#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
apt-get -y update
apt-get -y install haproxy=1.6.\*

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend sammykingx.tech
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 478987-web-01 54.160.65.63
        server 478987-web-02 100.24.206.208
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
service haproxy restart
