#!/usr/bin/env bash
# script displays list of currently running processes
# show all processes, for all users, including those which might not have a TTY
# Display a user-oriented format
# will Show process hierarchy

ps -a -x -u -f
