#!/usr/bin/env bash
# The script extends previous exercise command and displays line containing the bash word, this allowing you to easily get the PID of your Bash process
# You should not use pgrep
# shellcheck disable=SC2009

./1-list_your_processes | grep "bash"
